# docker-compose.yml
services:
  string_mcp:
    build: ./string_mcp
    ports:
      - "8001:8000"
    environment:
      - DOCKER_MODE=true
    restart: unless-stopped
    
  pride_mcp:
    build: ./pride_mcp  
    ports:
      - "8002:8000"
    environment:
      - DOCKER_MODE=true
    restart: unless-stopped
    
  biogrid_mcp:
    build: ./biogrid_mcp
    ports:
      - "8003:8000"
    environment:
      - BIOGRID_API_KEY=${BIOGRID_API_KEY}
      - DOCKER_MODE=true
    restart: unless-stopped
    
  cross_database_mcp:
    build: ./cross_database_mcp
    ports:
      - "8004:8000"
    environment:
      - DOCKER_MODE=true
      - STRING_MCP_URL=http://string_mcp:8000
      - PRIDE_MCP_URL=http://pride_mcp:8000
      - BIOGRID_MCP_URL=http://biogrid_mcp:8000
    depends_on:
      - string_mcp
      - pride_mcp
      - biogrid_mcp
    restart: unless-stopped

networks:
  default:
    name: mcp_network